### ISSUE TITLE
Search function in the documentation is not working

### ISSUE THREAD

**Issue by marijnkeijzer** [defSim/defSim#85]

**Comment by ikbentimkramer** [comment]
So the file `docs/language_data.js` is not included in `docs/search.html` which causes the search to break. The class `Stemmer` is defined in `language_data.js` and the search function needs this class to do its job. The patch below fixes this.

I do not like this particular solution, because it patches generated HTML. Ideally, simply rebuilding the documentation would fix this issue by running something like `sphinx-build -b html source docs`. However, while rebuilding does include the missing `language_data.js` in `search.html` exactly like this patch does, it also seems to remove mathjax from `search.html`, changes pretty much all other files in `docs/`, creates a couple of new ones, and throws about 50 warnings. I am not sure if any of these changes caused by rebuilding breaks something else. So I do think this patch is the best solution for now.

``` diff
diff --git a/docs/search.html b/docs/search.html
index 2b6c617..c346467 100644
--- a/docs/search.html
+++ b/docs/search.html
@@ -38,6 +38,7 @@
 
     
     <script type="text/javascript" src="_static/searchtools.js"></script>
+    <script type="text/javascript" src="_static/language_data.js"></script>
     <link rel="index" title="Index" href="genindex.html" />
     <link rel="search" title="Search" href="#" /> 
 </head>
@@ -230,4 +231,4 @@
 
 
 </body>
-</html>
\ No newline at end of file
+</html>
```

**Comment by dimaba** [comment]
ah! Thanks for figuring all of this out. @marijnkeijzer knows more about the documentation than I do, maybe he can take a look at this to see what the best solution is

**Comment by marijnkeijzer** [comment]
Thanks Tim! 

I upgraded to the newest version of readthedocs and rebuilt the documentation c1711ab1f060f9cbaa8db4497ced9ec0ff2a2317

Seems to work now
